export { default as HeroComponent } from "./hero"
export { default as Navbar } from "./navbar"
export { default as HireMe } from "./hireMe"
export { default as Projects } from "./projects"
export { default as Footer } from "./footer"